### ISSUE TITLE
Navigation widget

### ISSUE THREAD

**Issue by VideoTree** [mgsisk/webcomic#241]
Apologies for the question.

I am trying to make custom buttons for navigation in my site, I remember that it used to be different in the previous version and that you could just upload them in the customizer. I tried using the widgets for this in the webcomic navigation part but when I uploaded the images by the time I was done with it all of them were small and also everything was aligned left. How could I fix this?

Thank you, have a nice day

**Comment by Mihari** [comment]
Applying these CSS edits in the Sytlesheet section of the customizer will correct the issue: 
```css
.post-webcomic nav { text-align: center; }
.post-webcomic nav a { float: none; }
```
