### ISSUE TITLE
hiding nav links

### ISSUE THREAD

**Issue by MerrilyDuffy** [mgsisk/webcomic#98]
Hello,

I'm trying to recreate my site in a sandbox with the new version before upgrading, and have a minor question:

In version 3, one could hide navigation links that weren't needed on the first comic and last comic pages with:

``` css
.first-webcomic-link.current-webcomic,
.previous-webcomic-link.current-webcomic { visibility: hidden; }
.next-webcomic-link.current-webcomic,
.last-webcomic-link.current-webcomic { visibility: hidden; }
```

yet still be able click the image to navigate via this in the plugin:

``` php
<?php echo $this->get_the_webcomic_object( 'full', 'next' ); ?> 
```

In the newest version, hiding the links this way works just the same, except with the last/latest comic image, which is hidden along with the next and last links; I assume it is due to the $relative parameter 'next' in the_webcomic template tag? When I removed 'next' from the tag, the pic reappears, but now one can't click on the images to navigate, obviously.

Is it impossible with the new version to hide the links, while keeping the most recent comic visible, and keep the ability to click to navigate?

Thanks much,

Merrily
